# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 570af30dbef522df6dbab94908e30255c9ae8d04e7810c6a62d6c37d0c381fe00880bc2352ec661d881c7ed50cea98068b493971d7782533eb2ce9715a3d9fff

test:
  secret_key_base: 560429d04f21cc4e25a848f5555bf4ca2c7ef759e19901175d3b0068d29fc9d2b5a3485a69f9b7d4fd5689ca59bb1ca1b7518fdfd9c74f662f88ab14ef13a50e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
